config/routes.rb
Rails.application.routes.draw do
  
  root to: 'languages#index'
  resources :datacenters
  
  resources :countries
	
  resources :languages
  
   # API routes
  namespace :api do
    namespace :v1 do
      # resources :sessions, :only => [:create, :destroy]
		get 'datacenters', to: "datacenters#index"
		get 'datacenter(/:id)', to: "datacenters#show"
 	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :language
  validates :name, presence: true
end

app/models/datacenter.rb
class Datacenter < ApplicationRecord
  belongs_to :country
  validates :code, presence: true
  validates :code, uniqueness: true
  validates :servers_available, numericality: { greater_than: 0 }
  validates :servers_capacity, numericality: { greater_than: 0 }
end

app/models/language.rb
class Language < ApplicationRecord
	validates :name, presence: true
	validates :name, uniqueness: true
end

app/controllers/api/v1/datacenters_controller.rb
module Api
	module V1

	class DatacentersController < ApplicationController

		def index
			# @datacenters = Datacenter.all
			@datacenters = Datacenter.joins(:country).select('datacenters.*, countries.name as country')
			render json: @datacenters

		end

		def show
			@datacenter = Datacenter.joins(:country).select('datacenters.*, countries.name as country').where('datacenters.id = ?', params[:id])

			if @datacenter.size == 0
				render json: { message: "Record Not found"}, status: :not_found
			else
				render json: @datacenter
			end

		end
	end
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]
  
 
  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :language_id)
    end
end

app/controllers/datacenters_controller.rb
class DatacentersController < ApplicationController
  before_action :set_datacenter, only: [:show, :edit, :update, :destroy]

  # GET /datacenters
  # GET /datacenters.json
  def index
    @datacenters = Datacenter.all
  end

  # GET /datacenters/1
  # GET /datacenters/1.json
  def show
  end

  # GET /datacenters/new
  def new
    @datacenter = Datacenter.new
  end

  # GET /datacenters/1/edit
  def edit
  end

  # POST /datacenters
  # POST /datacenters.json
  def create
    @datacenter = Datacenter.new(datacenter_params)

    respond_to do |format|
      if @datacenter.save
        format.html { redirect_to @datacenter, notice: 'Datacenter was successfully created.' }
        format.json { render :show, status: :created, location: @datacenter }
      else
        format.html { render :new }
        format.json { render json: @datacenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datacenters/1
  # PATCH/PUT /datacenters/1.json
  def update
    respond_to do |format|
      if @datacenter.update(datacenter_params)
        format.html { redirect_to @datacenter, notice: 'Datacenter was successfully updated.' }
        format.json { render :show, status: :ok, location: @datacenter }
      else
        format.html { render :edit }
        format.json { render json: @datacenter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datacenters/1
  # DELETE /datacenters/1.json
  def destroy
    @datacenter.destroy
    respond_to do |format|
      format.html { redirect_to datacenters_url, notice: 'Datacenter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datacenter
      @datacenter = Datacenter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datacenter_params
      params.require(:datacenter).permit(:code, :servers_available, :servers_capacity, :country_id)
    end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/datacenters_helper.rb
module DatacentersHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
    <th><%= form.label :name %></th>
    <td><%= form.text_field :name, id: :country_name %></td>
  </tr>

  <tr>
    <th><%= form.label :language_id %></th>
    <td><%= form.select(:language_id, Language.all.map { |l| [l.name, l.id]}) %> <%= link_to 'Add New Language', new_language_path %></td>
   
  </tr>

  <tr>
    <td><%= form.submit %></td>
  </tr>
</table>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<div class="index">

<h1>Countries</h1>
<%= link_to 'New Country', new_country_path %>
<% if @countries == nil || @countries.size == 0 %>
 <h3> No Countries available. </h3>
<% else %>
<table class="listing">
 
    <tr class="header">
      <th>Name</th>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>


  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.language.name %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>



</div>

app/views/countries/new.html.erb
<div class="new">
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>
</div>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>View Language:</strong>
  <%= @country.language.name %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/datacenters/_form.html.erb
<%= form_with(model: datacenter, local: true) do |form| %>
  <% if datacenter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(datacenter.errors.count, "error") %> prohibited this datacenter from being saved:</h2>

      <ul>
      <% datacenter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
   <th> <%= form.label :code %></th>
    <td><%= form.text_field :code, id: :datacenter_code %></td>
  </tr>

  <tr>
    <th><%= form.label :servers_available %></th>
    <td><%= form.number_field :servers_available, id: :datacenter_servers_available %></td>
  </tr>

  <tr>
    <th><%= form.label :servers_capacity %></th>
    <td><%= form.number_field :servers_capacity, id: :datacenter_servers_capacity %>(in TB)</td>
  </tr>

  <tr>
    <th><%= form.label :country_id %></th>
   <td><%= form.select(:country_id, Country.all.map { |c| [c.name, c.id]}) %>   <%= link_to 'Add New Country', new_country_path %></td>
  </tr>

  <tr>
    <td class = "center">
    <%= form.submit %>
  </td>
  </tr>
</table>
<% end %>

app/views/datacenters/edit.html.erb
<h1>Edit DataCenter</h1>

<%= render 'form', datacenter: @datacenter %>

<%= link_to 'Show', @datacenter %> |
<%= link_to 'Back', datacenters_path %>

app/views/datacenters/index.html.erb
<div class="index">

<h1>DataCenters</h1>
<%= link_to 'New Datacenter', new_datacenter_path %><br />
<% if @datacenters == nil || @datacenters.size == 0 %>
 <h3> No DataCenters available. </h3>
<% else %>
<table class="listing">

    <tr class = "header">
      <th>Code</th>
      <th>Servers available</th>
      <th>Servers capacity</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>


  <tbody>
    <% @datacenters.each do |datacenter| %>
      <tr>
        <td><%= datacenter.code %></td>
        <td><%= datacenter.servers_available %></td>
        <td><%= datacenter.servers_capacity %></td>
        <td><%= datacenter.country.name %></td>
        <td><%= link_to 'Show', datacenter %></td>
        <td><%= link_to 'Edit', edit_datacenter_path(datacenter) %></td>
        <td><%= link_to 'Destroy', datacenter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>


</div>

app/views/datacenters/new.html.erb
<div class="new">
<h1>New DataCenter</h1>

<%= render 'form', datacenter: @datacenter %>

<%= link_to 'Back', datacenters_path, :class => "back-link" %>
</div>

app/views/datacenters/show.html.erb
<%= link_to 'Edit', edit_datacenter_path(@datacenter)%> |
<%= link_to 'Back', datacenters_path %>
<div class="show">
<h2> View DataCenter </h2>
<table>
<tr>
  <th>Code:</th>
  <td><%= @datacenter.code %></td>
</tr>

<tr>
  <th>Servers available:</th>
  <td><%= @datacenter.servers_available %></td>
</tr>

<tr>
  <th>Servers capacity:</th>
  <td><%= @datacenter.servers_capacity %>TB</td>
</tr>

<tr>
  <th>Country:</th>
  <td><%= @datacenter.country.name %></td>
</tr>

</table>

</div>

app/views/languages/_form.html.erb
<%= form_with(model: language, local: true) do |form| %>
  <% if language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
    <td><%= form.label :name %></td>
    <td><%= form.text_field :name, id: :language_name %></td>
  </tr>

  <tr class="actions">
    <td><%= form.submit %></td>
    <td></td>
  </tr>
  </table>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<div class="index">

<h1>Languages</h1>
<%= link_to 'New Language', new_language_path %>
<% if @languages == nil || @languages.size == 0 %>
 <h3> No Languages available. </h3>
<% else %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.name %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
</div>

app/views/languages/new.html.erb
<div class="new">
<h1>New Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Back', languages_path %>
</div>

app/views/languages/show.html.erb
<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>

<div class="show">

<table>
	<tr>
		<th>View Language</th>
	</tr>
	<tr>
		<th> </th>
	</tr>
	<tr>
  <th>Name:</th>
  <td><%= @language.name %></td>
</tr>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DatacenterProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
       <%= stylesheet_link_tag('admin', :media => 'all') %>
  </head>

  <body>
  	 <div id="header">
      <h1>DataCenter Application</h1>
    </div>
    <div id="main">
  	<% if !flash[:notice].blank? %>
  	<div class="notice">
  		<%= flash[:notice] %>
  	</div>
  	<% end %>
    <div id="content">
      <%= link_to 'Data Centers', datacenters_path %> | <%= link_to 'Countries', countries_path %> | <%= link_to 'Languages', languages_path %>
      <br />
      <br />
    <%= yield %>
  </div>
  </div>
  <div id="footer">
    <p id="copyright">@copy; Gowri Damarla</p>
  </div>
  </body>
</html>